//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsUnitTest.PublicacaoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noticia", Namespace="http://schemas.datacontract.org/2004/07/News.DomainModel.Aggregations.NoticiaAggr" +
        "egate")]
    [System.SerializableAttribute()]
    public partial class Noticia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewsUnitTest.PublicacaoService.Foto FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PublicacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conteudo {
            get {
                return this.ConteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true)) {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expiracao {
            get {
                return this.ExpiracaoField;
            }
            set {
                if ((this.ExpiracaoField.Equals(value) != true)) {
                    this.ExpiracaoField = value;
                    this.RaisePropertyChanged("Expiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewsUnitTest.PublicacaoService.Foto Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Publicacao {
            get {
                return this.PublicacaoField;
            }
            set {
                if ((this.PublicacaoField.Equals(value) != true)) {
                    this.PublicacaoField = value;
                    this.RaisePropertyChanged("Publicacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Foto", Namespace="http://schemas.datacontract.org/2004/07/News.DomainModel.Aggregations.NoticiaAggr" +
        "egate")]
    [System.SerializableAttribute()]
    public partial class Foto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CriacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotografoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ImagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Criacao {
            get {
                return this.CriacaoField;
            }
            set {
                if ((this.CriacaoField.Equals(value) != true)) {
                    this.CriacaoField = value;
                    this.RaisePropertyChanged("Criacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fotografo {
            get {
                return this.FotografoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotografoField, value) != true)) {
                    this.FotografoField = value;
                    this.RaisePropertyChanged("Fotografo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri Imagem {
            get {
                return this.ImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemField, value) != true)) {
                    this.ImagemField = value;
                    this.RaisePropertyChanged("Imagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublicacaoService.IPublicacaoService")]
    public interface IPublicacaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicacaoService/PublicarNoticia", ReplyAction="http://tempuri.org/IPublicacaoService/PublicarNoticiaResponse")]
        bool PublicarNoticia(NewsUnitTest.PublicacaoService.Noticia noticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicacaoService/PublicarNoticia", ReplyAction="http://tempuri.org/IPublicacaoService/PublicarNoticiaResponse")]
        System.Threading.Tasks.Task<bool> PublicarNoticiaAsync(NewsUnitTest.PublicacaoService.Noticia noticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicacaoService/ObterNoticiasPublicadas", ReplyAction="http://tempuri.org/IPublicacaoService/ObterNoticiasPublicadasResponse")]
        NewsUnitTest.PublicacaoService.Noticia[] ObterNoticiasPublicadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicacaoService/ObterNoticiasPublicadas", ReplyAction="http://tempuri.org/IPublicacaoService/ObterNoticiasPublicadasResponse")]
        System.Threading.Tasks.Task<NewsUnitTest.PublicacaoService.Noticia[]> ObterNoticiasPublicadasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicacaoServiceChannel : NewsUnitTest.PublicacaoService.IPublicacaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicacaoServiceClient : System.ServiceModel.ClientBase<NewsUnitTest.PublicacaoService.IPublicacaoService>, NewsUnitTest.PublicacaoService.IPublicacaoService {
        
        public PublicacaoServiceClient() {
        }
        
        public PublicacaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicacaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicacaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicacaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PublicarNoticia(NewsUnitTest.PublicacaoService.Noticia noticia) {
            return base.Channel.PublicarNoticia(noticia);
        }
        
        public System.Threading.Tasks.Task<bool> PublicarNoticiaAsync(NewsUnitTest.PublicacaoService.Noticia noticia) {
            return base.Channel.PublicarNoticiaAsync(noticia);
        }
        
        public NewsUnitTest.PublicacaoService.Noticia[] ObterNoticiasPublicadas() {
            return base.Channel.ObterNoticiasPublicadas();
        }
        
        public System.Threading.Tasks.Task<NewsUnitTest.PublicacaoService.Noticia[]> ObterNoticiasPublicadasAsync() {
            return base.Channel.ObterNoticiasPublicadasAsync();
        }
    }
}
